config/routes.rb
Rails.application.routes.draw do

  resources :hosted_feeds

  get 'p/:slug' => 'slug#show'

  resources :podcasts

  get '/' => 'splash#welcome'

  get 'splash/welcome'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/models/hosted_feed.rb
class HostedFeed < ActiveRecord::Base
  has_many :podcasts
  belongs_to :user
  mount_uploader :rss_feed_file, RssFeedFileUploader
end

app/controllers/hosted_feeds_controller.rb
class HostedFeedsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_hosted_feed, only: [:show, :edit, :update, :destroy]

  # GET /hosted_feeds
  # GET /hosted_feeds.json
  def index
    @hosted_feeds = HostedFeed.all
  end

  # GET /hosted_feeds/1
  # GET /hosted_feeds/1.json
  def show
  end

  # GET /hosted_feeds/new
  def new
    @hosted_feed = HostedFeed.new
  end

  # GET /hosted_feeds/1/edit
  def edit
  end

  # POST /hosted_feeds
  # POST /hosted_feeds.json
  def create
    @hosted_feed = HostedFeed.new(hosted_feed_params)
    @hosted_feed.user = current_user

    respond_to do |format|
      if @hosted_feed.save
        format.html { redirect_to @hosted_feed, notice: 'Hosted feed was successfully created.' }
        format.json { render :show, status: :created, location: @hosted_feed }
      else
        format.html { render :new }
        format.json { render json: @hosted_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosted_feeds/1
  # PATCH/PUT /hosted_feeds/1.json
  def update
    respond_to do |format|
      if @hosted_feed.update(hosted_feed_params)
        format.html { redirect_to @hosted_feed, notice: 'Hosted feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @hosted_feed }
      else
        format.html { render :edit }
        format.json { render json: @hosted_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosted_feeds/1
  # DELETE /hosted_feeds/1.json
  def destroy
    @hosted_feed.destroy
    respond_to do |format|
      format.html { redirect_to hosted_feeds_url, notice: 'Hosted feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hosted_feed
      @hosted_feed = HostedFeed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hosted_feed_params
      params.require(:hosted_feed).permit(:title, :slug, :description, :rss_feed_file)
    end
end

app/helpers/hosted_feeds_helper.rb
module HostedFeedsHelper
end

app/views/hosted_feeds/_form.html.erb
<%= form_for(@hosted_feed) do |f| %>
  <% if @hosted_feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hosted_feed.errors.count, "error") %> prohibited this hosted_feed from being saved:</h2>

      <ul>
      <% @hosted_feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rss_feed_file %><br>
    <%= f.file_field :rss_feed_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hosted_feeds/edit.html.erb
<h1>Editing hosted_feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @hosted_feed %> |
<%= link_to 'Back', hosted_feeds_path %>

app/views/hosted_feeds/index.html.erb
<h1>Listing hosted_feeds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hosted_feeds.each do |hosted_feed| %>
      <tr>
        <td><%= hosted_feed.title %></td>
        <td><%= hosted_feed.slug %></td>
        <td><%= hosted_feed.description %></td>
        <td><%= link_to 'Show', hosted_feed %></td>
        <td><%= link_to 'Edit', edit_hosted_feed_path(hosted_feed) %></td>
        <td><%= link_to 'Destroy', hosted_feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hosted feed', new_hosted_feed_path %>

app/views/hosted_feeds/new.html.erb
<h1>New hosted_feed</h1>

<%= render 'form' %>

<%= link_to 'Back', hosted_feeds_path %>

app/views/hosted_feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @hosted_feed.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @hosted_feed.slug %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hosted_feed.description %>
</p>

<%= link_to 'Edit', edit_hosted_feed_path(@hosted_feed) %> |
<%= link_to 'Back', hosted_feeds_path %>