config/routes.rb
Rails.application.routes.draw do

  resources :hosted_feeds

  get 'p/:slug' => 'slug#show'

  resources :podcasts

  get '/' => 'splash#welcome'

  get 'splash/welcome'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  belongs_to :user
  belongs_to :hosted_feed  # because it has one feed,
                    # but a feed can have more than one
                    # podcast model because a feed can be
                    # reused for other how-tos
  # validates :feed, format: { with : /\Ahttp:\/\//}
  validates :feed, format: { with: /\Ahttp:\/\//}
end

app/controllers/podcasts_controller.rb
require 'ostruct'

class PodcastsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]

  # GET /podcasts
  # GET /podcasts.json
  def index
    # @podcasts = Podcast.all
    @podcasts = Podcast.where(:user_id => current_user.id)
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
    @hosted_feeds = HostedFeed.where(:user_id => current_user.id)
    @hosted_feeds.push(OpenStruct.new(title: 'Create New', id: 'new'))
  end

  # GET /podcasts/1/edit
  def edit
    @hosted_feeds = HostedFeed.where(:user_id => current_user.id)
    @hosted_feeds.push(OpenStruct.new(title: 'Create New', id: 'new'))
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)
    @podcast.user_id = current_user.id

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1
  # PATCH/PUT /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: 'Podcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def podcast_params
      params.require(:podcast).permit(:slug, :course_name, :podcast_name, :feed, :description, :hosted_feed_id)
    end
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/podcasts/_form.html.erb
<%= form_for(@podcast) do |f| %>
  <% if @podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
      <% @podcast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug, :class => 'topcoat-text-input' %>
  </div>
  <div class="field">
    <%= f.label :course_name %><br>
    <%= f.text_field :course_name, :class => 'topcoat-text-input'  %>
  </div>
  <div class="field">
    <%= f.label :podcast_name %><br>
    <%= f.text_field :podcast_name, :class => 'topcoat-text-input'  %>
  </div>
  <div class="field">
    <%= f.label 'Feed Url' %><br>
    <span id="feed_url_">
      <%= f.text_field :feed, :class => 'topcoat-text-input'  %>
    <span>
  </div>
  <div class="field">
    <%= link_to "(or create your own feed)", new_hosted_feed_path %>
    <%= collection_select(:podcast, :hosted_feed_id,  @hosted_feeds, :id, :title, {prompt: 'Your Feeds'})  %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => 'topcoat-textarea' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/podcasts/edit.html.erb
<h1>Editing podcast</h1>

<%= render 'form' %>

<%= link_to 'Show', @podcast %> |
<%= link_to 'Back', podcasts_path %>

app/views/podcasts/index.html.erb
<div class="content">
  <header> <h1> Listing podcasts </h1> </header>

  <table>
    <thead>
      <tr>
        <th>Slug</th>
        <th>Course name</th>
        <th>Podcast name</th>
        <th>Feed</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @podcasts.each do |podcast| %>
        <tr>
          <td><%= podcast.slug %></td>
          <td><%= podcast.course_name %></td>
          <td><%= podcast.podcast_name %></td>
          <td><%= podcast.feed %></td>
          <td><%= podcast.description %></td>
          <td><%= link_to 'Show', podcast %></td>
          <td><%= link_to 'Edit', edit_podcast_path(podcast) %></td>
          <td><%= link_to 'Destroy', podcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Podcast', new_podcast_path %>
</div>

app/views/podcasts/new.html.erb
<div class='center'>
<h1>New podcast</h1>

<%= render 'form' %>

<%= link_to 'Back', podcasts_path %>
</div>

app/views/podcasts/show-old.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Slug:</strong>
  <%= @podcast.slug %>
</p>

<p>
  <strong>Course name:</strong>
  <%= @podcast.course_name %>
</p>

<p>
  <strong>Podcast name:</strong>
  <%= @podcast.podcast_name %>
</p>

<p>
  <strong>Feed:</strong>
  <%= @podcast.feed %>
</p>

<p>
  <strong>Description:</strong>
  <%= @podcast.description %>
</p>

<%= link_to 'Edit', edit_podcast_path(@podcast) %> |
<%= link_to 'Back', podcasts_path %>

app/views/podcasts/show.html.erb
<div class="desktop">
  View as <a id="view-ios"> iOS</a>
  View as <a id="view-android"> Android</a>
</div>
<div class="description">
  <h1>
    Podcasts
  </h1>
  <p> 
    <strong> Instructions for <%= @podcast.course_name %>: </strong> 
    <%= @podcast.description %>
  </p>
  <div class="center">
    <p>Podcast App</p>
    <img class="android center" src="/img/beyondpod-demo.png" width="90%">
    <img class="iOS center" src="/img/ios-demo.png" width="90%">
  </div>
</div>
<div class="step step1">
  <h2> Step 1 </h2>
  <p>First download the App.</p>
  <a class="iOS" href="https://itunes.apple.com/en/app/podcasts/id525463029?mt=8">
    podcasts for iOS 
    <img src="/img/Download_on_the_App_Store_Badge_HK_TW_135x40.png">
</a>
  <a class="android" href="https://play.google.com/store/apps/details?id=mobi.beyondpod">
    beyondpod
    <img class="android"
       alt="Get it on Google Play"
       src="https://developer.android.com/images/brand/zh-tw_generic_rgb_wo_45.png" />
  </a>
</div>
<div class="step step2">
  <h2> Step 2 </h2>
  <div class='android'>
    <p> Add the feed. Inside your App, copy and paste the feed's link. <strong>Note: do not paste it into your browser, you must paste it into the App that you just downloaded!</strong></p>
    <div class="sub-step">
      <p>1. Click <strong>Add Feed</strong></p>
      <img src="/img/beyondpod-instructions-arrow-1.png" width="90%">
    </div>
    <div class="sub-step">
      <p>2. Click <strong>Search</strong></p>
      <img src="/img/beyondpod-instructions-arrow-2.png" width="90%">
    </div>
    <div class="sub-step">
      <p>3. Paste in the feed's address. (Be sure to include http://!)</p>
      <pre class="link-code center"><span> <%= @podcast.feed %> </span></pre>
      <img src="/img/beyondpod-instructions-arrow-3.png" width="90%">
    </div>
  </div>
  <div class="iOS">
    <p> <strong> After you download the App, </strong> click this link to subscribe to the podcast" </p>
    <pre class="link-code center"><span><a href="<%= @podcast.feed %>"> <%= @podcast.feed %> </a></span></pre>
  </div>
</div>

<div class="step step3 iOS">
  <h2>Step 3</h2>
  <p> Add old episodes 加入舊的單集 </p>
    <div class="sub-step">
      <img src="/img/ios-add-episodes-arrow-1.png" width="90%">
    </div>
</div>